# -*- coding: utf-8 -*-
"""ETL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CBwA20HvyhxcuHCdPDKlg2BRG7VTh-eM

**Extracting Data Through URL**
"""

from urllib.request import urlopen

"""Storing in txt file"""

with open("data.txt", "w") as external_file:
    add_text = urlopen("https://www.amfiindia.com/spages/NAVOpen.txt?t=19022022062418").read()
    print(add_text, file=external_file)
    external_file.close()

"""Printing txt to check data"""

a_file = open("data.txt")

lines = a_file.readlines()
for line in lines:
    print(line)

"""Splitting Data into Rows and Columns 

- Second line gives the data of Columns
- Fourth line gives the data of row
- Every blank line indicates a change in row and column
"""

f = open('data.txt','rt')
a = [[int(token) for token in line.split()] for line in f.readlines()[::2]]

"""Once data segregation is done we store it as a csv file

"""

import pandas as pd

read_file = pd.read_csv (r'C:\Users\Ron\Desktop\Test\Data.txt')
read_file.to_csv (r'C:\Users\Ron\Desktop\Test\Data.csv', index=None)

"""**Connecting to Mysql and Storing** **Data**"""

import pandas as pd
import mysql.connector as sql

#reading csv file
df = pd.data.csv

#check how many rows and columns we have
df.shape

#understand the data types of our dataframe
df.dtypes

"""Storing the data in MySQL"""

#create our credentials
db=’mysql’
user=’db_admin’
paswd=’db_admin_password'
host=’localhost’

#create the connection object
conn = sql.connect(db=db,user=user,host=host,password=paswd,use_unicode=True,
charset=”utf8", auth_plugin=’mysql_native_password’)

"""Reading and inserting data in CHUNKS"""

# read data in chunks
for chunk in pd.read_csv(,
                         dtype={}):
    
    # zip the data
    data = list(zip.to_numpy()))
    
    # insert data into db
    try:
        cur.executemany(insert_query,data)
        conn.commit()
        print('success')
    
    except (sql.Error,sql.Warning) as e:
        conn.close()
        print(e)